#!/usr/bin/env bash
set -euo pipefail

_usage() {
  echo "running the server"
  echo "    up        start the server in development mode"
  echo ""
  echo "testing code"
  echo "    test      run tests, accepts test names as arguments"
  echo "    cov       run tests with coverage"
  echo ""
  echo "installing Python requirements"
  echo "    pipi      without argument: installs packages defined in requirements.txt and requirements-local.txt"
  echo "              with argument:    installs given requirement"
  echo ""
  echo "migrations"
  echo "    migrate   run pending migrations"
  echo "    makemig   make Django migrations"
  echo "    sqlmig    show SQL of migration without executing it"
  echo ""
  echo "tools"
  echo "    black     run black"
  echo "    isort     run isort"
  exit 1
}

# show usage if no argument is given
arg=${1:-}
shift || _usage

case ${arg} in
up|run|server|runserver)
  python src/manage.py runserver 0.0.0.0:8000
;;
test)
  PYTHONPATH=src pytest "$@"
;;
migrate)
  python src/manage.py migrate "$@"
;;
makemigrations|makemigration|makemig)
  python src/manage.py makemigrations "$@"
;;
sqlmig|sqlmigrate|sqlmigration)
  python src/manage.py sqlmigrate "$@"
;;
*)
  _usage
;;
esac
